### ISSUE TITLE
Investigate - Backend PostgreSQL hosting options

### ISSUE THREAD

**Issue by majdbrayhaus** [majdbrayhaus/brayhaus#10]
**Investigate options like:**

- Heroku
- AWS
- Google
- ElephantSQL

**Comment by Quinten97** [comment]
## Backend PostgresSQL options

[AWS](https://aws.amazon.com/free/?all-free-tier.sort-by=item.additionalFields.SortRank&all-free-tier.sort-order=asc&awsf.Free%20Tier%20Types=*all&awsf.Free%20Tier%20Categories=*all)

- Several Options (RDS seems most likely)
- Free 750 Hours a month for almost all of their DB hosting options for the first year.

[Heroku](https://www.heroku.com/pricing)

- Row limit 10K
- 20 connections

[Google Cloud](https://cloud.google.com/free/docs/gcp-free-tier#free-tier)

- 28 hours per day of ["F" instances](https://cloud.google.com/appengine/docs/standard#instance_classes)
- 9 hours per day of ["B" instances](https://cloud.google.com/appengine/docs/standard#instance_classes)
- 1 GB of egress per day

[ElephantSQL](https://www.elephantsql.com/plans.html)

- 20MB data
- 5 concurrent connections
- Shared Server resources
