### ISSUE TITLE
Investigate how to limit auth for schools to be with that school's students

### ISSUE THREAD

**Issue by majdbrayhaus** [majdbrayhaus/brayhaus#11]
How to ensure that only students of a certain school can use the service? 

Software like this is typically licensed to a whole county and not just a school. 
Typically, a county will have a unique email address

**Comment by Quinten97** [comment]
Google Sign-in would be a good way to accomplish this, Typically school systems use google already to generate student and faculty accounts so this would integrate easily, and googles API allows us to easily grab the user's information for our own database. The school systems will typically have their own email tags (ex: @gscs.org) that we can use to whitelist with county by county or if a singular school can limit the number of accounts to the number of students or they could even pull the student's email accounts and we could create a whitelist for those specific accounts which would have to be refreshed every year as students would be leaving to other schools depending on grade.

**Comment by Quinten97** [comment]
Documentation added to the wiki
