### ISSUE TITLE
Investigate implementation of coloring an SVG

### ISSUE THREAD

**Issue by majdbrayhaus** [majdbrayhaus/brayhaus#24]

**Comment by majdbrayhaus** [comment]
1. React tutorial flood fill
2. Canvas overlayed with an svg

Possibly combine both

**Comment by majdbrayhaus** [comment]
https://uxdesign.cc/5-steps-to-create-a-simple-digital-coloring-book-in-react-3d4f5b2af822

**Comment by Quinten97** [comment]
https://codepen.io/Quinten97/pen/KKyZjRo

**Comment by carnoldcoding** [comment]
Codepen by Quinten provided a pure JS solution to the issue. I'd say that's enough to warrant the end of the investigation and move towards implementation.
