### ISSUE TITLE
Design - Provide all Brayhaus Logos & Assets

### ISSUE THREAD

**Issue by majdbrayhaus** [majdbrayhaus/brayhaus#25]
Please post all relevant assets as an attachment to this ticket and in discord

**Comment by mrbray** [comment]
https://mrbray-my.sharepoint.com/:f:/p/jesse/EtuqLtTQ_CFBgWDAOuf0GBwBfeTtL3_aS08qn0C2yqlGnA?e=zdeVUt

all assets will and are in this folder. please let me know if you require anything specific via file type not found and I will happily add it. :)
