### ISSUE TITLE
Design - Pickout Brayhaus Colors

### ISSUE THREAD

**Issue by majdbrayhaus** [majdbrayhaus/brayhaus#6]
**Objective**
Pick out the colors for brayhaus and add their different shades

**Relevant Info & resources**
Figma:
https://www.figma.com/file/Pwtt5dY4xdBVNx1C7vVkYL/Brayhaus-MVP?node-id=3%3A223

**Comment by majdbrayhaus** [comment]
**Quinten**: Find colors from children toys

**Comment by mrbray** [comment]
https://mrbray-my.sharepoint.com/:f:/p/jesse/EtuqLtTQ_CFBgWDAOuf0GBwBfeTtL3_aS08qn0C2yqlGnA?e=zdeVUt

link to assests
